### ISSUE TITLE
Home Assistant Miele Stopped turning on and off coffee machine, action response 204

### ISSUE THREAD

**Issue by scottleestrange** [astrandb/miele#659]
### The problem

Home Assistant Miele Stopped turning on and off coffee machine, action response 204
Core 2015.3.4
OS 15.0
Miele 2025.1

The integration correctly reads the state of the machine, but will not update (turn on and off). 

2025-03-31 15:25:39.960 DEBUG (MainThread) [custom_components.miele] Finished fetching miele data in 0.481 seconds (success: True)
2025-03-31 15:25:39.960 DEBUG (MainThread) [custom_components.miele] Miele devices in API account: ['000153063181']
2025-03-31 15:25:40.179 DEBUG (MainThread) [custom_components.miele.binary_sensor] init sensor 000153063181
2025-03-31 15:25:40.179 DEBUG (MainThread) [custom_components.miele.binary_sensor] init sensor 000153063181
2025-03-31 15:25:40.179 DEBUG (MainThread) [custom_components.miele.binary_sensor] init sensor 000153063181
2025-03-31 15:25:40.179 DEBUG (MainThread) [custom_components.miele.binary_sensor] init sensor 000153063181
2025-03-31 15:25:40.180 DEBUG (MainThread) [custom_components.miele.binary_sensor] init sensor 000153063181
2025-03-31 15:25:40.189 DEBUG (MainThread) [custom_components.miele.light] Init light 000153063181
2025-03-31 15:25:40.194 DEBUG (MainThread) [custom_components.miele.sensor] init sensor 000153063181
2025-03-31 15:25:40.194 DEBUG (MainThread) [custom_components.miele.sensor] init sensor 000153063181
2025-03-31 15:25:40.194 DEBUG (MainThread) [custom_components.miele.sensor] init sensor 000153063181
2025-03-31 15:25:40.195 DEBUG (MainThread) [custom_components.miele.sensor] init sensor 000153063181
2025-03-31 15:25:40.204 DEBUG (MainThread) [custom_components.miele.switch] init switch 000153063181
2025-03-31 15:25:40.386 DEBUG (MainThread) [custom_components.miele] Manually updated miele data
2025-03-31 15:25:40.387 DEBUG (MainThread) [custom_components.miele] Manually updated miele data
2025-03-31 15:25:50.880 DEBUG (MainThread) [custom_components.miele.switch] turn_off -> kwargs: {}
2025-03-31 15:25:50.880 DEBUG (MainThread) [pymiele.pymiele] send_action serial: 000153063181, data: {'powerOff': True}
2025-03-31 15:25:51.395 DEBUG (MainThread) [pymiele.pymiele] send_action res: 204
2025-03-31 15:26:40.456 DEBUG (MainThread) [custom_components.miele] Finished fetching miele data in 0.452 seconds (success: True)
2025-03-31 15:27:40.464 DEBUG (MainThread) [custom_components.miele] Finished fetching miele data in 0.460 seconds (success: True)
2025-03-31 15:28:40.539 DEBUG (MainThread) [custom_components.miele] Finished fetching miele data in 0.534 seconds (success: True)
2025-03-31 15:28:41.209 DEBUG (MainThread) [custom_components.miele.switch] turn_off -> kwargs: {}
2025-03-31 15:28:41.210 DEBUG (MainThread) [pymiele.pymiele] send_action serial: 000153063181, data: {'powerOff': True}
2025-03-31 15:28:41.401 DEBUG (MainThread) [pymiele.pymiele] send_action res: 204
2025-03-31 15:29:40.493 DEBUG (MainThread) [custom_components.miele] Finished fetching miele data in 0.488 seconds 

### Version of miele integration having the issue?

2025.1

### Version of Home Assistant Core having the issue?

2025.3.4

### Anything in the logs that might be useful for us?

```txt
2025-03-31 15:25:39.960 DEBUG (MainThread) [custom_components.miele] Finished fetching miele data in 0.481 seconds (success: True)
2025-03-31 15:25:39.960 DEBUG (MainThread) [custom_components.miele] Miele devices in API account: ['000153063181']
2025-03-31 15:25:40.179 DEBUG (MainThread) [custom_components.miele.binary_sensor] init sensor 000153063181
2025-03-31 15:25:40.179 DEBUG (MainThread) [custom_components.miele.binary_sensor] init sensor 000153063181
2025-03-31 15:25:40.179 DEBUG (MainThread) [custom_components.miele.binary_sensor] init sensor 000153063181
2025-03-31 15:25:40.179 DEBUG (MainThread) [custom_components.miele.binary_sensor] init sensor 000153063181
2025-03-31 15:25:40.180 DEBUG (MainThread) [custom_components.miele.binary_sensor] init sensor 000153063181
2025-03-31 15:25:40.189 DEBUG (MainThread) [custom_components.miele.light] Init light 000153063181
2025-03-31 15:25:40.194 DEBUG (MainThread) [custom_components.miele.sensor] init sensor 000153063181
2025-03-31 15:25:40.194 DEBUG (MainThread) [custom_components.miele.sensor] init sensor 000153063181
2025-03-31 15:25:40.194 DEBUG (MainThread) [custom_components.miele.sensor] init sensor 000153063181
2025-03-31 15:25:40.195 DEBUG (MainThread) [custom_components.miele.sensor] init sensor 000153063181
2025-03-31 15:25:40.204 DEBUG (MainThread) [custom_components.miele.switch] init switch 000153063181
2025-03-31 15:25:40.386 DEBUG (MainThread) [custom_components.miele] Manually updated miele data
2025-03-31 15:25:40.387 DEBUG (MainThread) [custom_components.miele] Manually updated miele data
2025-03-31 15:25:50.880 DEBUG (MainThread) [custom_components.miele.switch] turn_off -> kwargs: {}
2025-03-31 15:25:50.880 DEBUG (MainThread) [pymiele.pymiele] send_action serial: 000153063181, data: {'powerOff': True}
2025-03-31 15:25:51.395 DEBUG (MainThread) [pymiele.pymiele] send_action res: 204
2025-03-31 15:26:40.456 DEBUG (MainThread) [custom_components.miele] Finished fetching miele data in 0.452 seconds (success: True)
2025-03-31 15:27:40.464 DEBUG (MainThread) [custom_components.miele] Finished fetching miele data in 0.460 seconds (success: True)
2025-03-31 15:28:40.539 DEBUG (MainThread) [custom_components.miele] Finished fetching miele data in 0.534 seconds (success: True)
2025-03-31 15:28:41.209 DEBUG (MainThread) [custom_components.miele.switch] turn_off -> kwargs: {}
2025-03-31 15:28:41.210 DEBUG (MainThread) [pymiele.pymiele] send_action serial: 000153063181, data: {'powerOff': True}
2025-03-31 15:28:41.401 DEBUG (MainThread) [pymiele.pymiele] send_action res: 204
2025-03-31 15:29:40.493 DEBUG (MainThread) [custom_components.miele] Finished fetching miele data in 0.488 seconds (success: True)
2025-03-31 15:30:40.468 DEBUG (MainThread) [custom_components.miele] Finished fetching miele data in 0.463 seconds
```

**Comment by scottleestrange** [comment]
Additional information.  I completely reset the app, removed and set up new token. Same behavior.  I did not that the coffee machine light will go on and off.  However power on does not work.  All sensors work and get brought down

**Comment by scottleestrange** [comment]
[config_entry-miele-01JQQEF60RBC38CR90TMM60PZT.json](https://github.com/user-attachments/files/19544511/config_entry-miele-01JQQEF60RBC38CR90TMM60PZT.json)
[home-assistant_miele_2025-04-01T03-09-47.208Z.log](https://github.com/user-attachments/files/19544512/home-assistant_miele_2025-04-01T03-09-47.208Z.log)

**Comment by astrandb** [comment]
Same problem as #655 
The API is responding with 204 which is the expected code when the command is accepted. However the command is not resulting in any change on the device.
Error 500 means that the Miele server has internal probloems. 400 is often returned when the command cannot be executed, e.g a powerOn action when the device is already in On state.
Nothing has changed in the integration but the Miele API has suddenly started to fail. The issue is reported to Miele but I have not got any response ye.

**Comment by astrandb** [comment]
Miele has confirmed that there is a problem in the API and they are working on a fix. Hopfully it can be deployed within a couple of days.

**Comment by astrandb** [comment]
Just got confirmation from Miele that their fix is deployed. Power On/Off works again for my washing machine. 😄

**Comment by scottleestrange** [comment]
Works for my coffee machine too

**Comment by Jabbo16** [comment]
Can confirm that it works for my coffee machine since this morning, thanks @astrandb 👍

**Comment by Corpsafin** [comment]
> Только что получил подтверждение от Miele, что их исправление запущено. Включение/выключение питания снова работает на моей стиральной машине. 😄

Do you have a Home Assistant that just turns on and off the coffee machine and the lights? It is not possible to add the preparation of different drinks, for example: latte, cappuccino and others using the Home assistant remotely.

**Comment by Corpsafin** [comment]
![Image](https://github.com/user-attachments/assets/af30239b-2cf9-45e7-8e31-c7a56ee8a369) I found the drinks I need, but I still can't figure out if it's possible to start making a drink with the help of a home assistant
